### ISSUE TITLE
Provide autowrapping for comments, if line length indicator is active

### ISSUE THREAD

**Issue by numeredev** [numere-org/NumeRe#16]
### DESCRIPTION
**What does your feature request improve on? Please describe.**
Automatic line wrapping would render the line length indicator far more usable than it currently is.

**Describe the solution you'd like**
Provide an option and functionality to handle the line wrapping of (documentation) comments, if the user activated the line length indicator (like in MATLAB). Should be active, if the user adds a character somewhere in a comment line. If a character is removed, it should not do anything. Style has to be copied from the previous line (keeping documentation comments).

**Additional context**
Migrated from here: https://sourceforge.net/p/numere/tickets/775/

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
Can be linked into the `NumeReEditor::OnChar()` event handler. Use the `NumeReEditor::isStyleType()` function to detect, whether the cursor is currently within a comment line or a comment block (might also be one char right of that -- check that) and if the line length indicator is active and if the line length is longer than the length indicator. Calculate then a correct linebreak position (you may use an adaption of `NumeReEditor::addLinebreaks()` to do that) and insert the line break as `"\r\n"`.

If the following line is also a comment line (check, whether the style values are identical), then prefix the wrapped contents to this line (possibly creating a recursion). Otherwise simply create a new line with the corresponding style type.

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by MarkRamp** [comment]
![image](https://github.com/numere-org/NumeRe/assets/40352159/30e80be7-ab33-4790-920b-24eedaece151)
This is the line indicator option, isn't it?

**Comment by numeredev** [comment]
> ![image](https://user-images.githubusercontent.com/40352159/269603129-30e80be7-ab33-4790-920b-24eedaece151.png) This is the line indicator option, isn't it?

Exactly

**Comment by numeredev** [comment]
> I'm struggling currently to find the variable which will tell me if line indicator is on/off. Where can I find it?

`m_options->getSettings()[SETTING_B_LINELENGTH].active()`

**Comment by MarkRamp** [comment]
Kannst du mir mal erklären, warum GetCurrentPos() hier 519 (print ist in OnChar Event von editor.cpp) zurückgibt? 

![image](https://github.com/numere-org/NumeRe/assets/40352159/6eed4915-d740-44ca-93d5-6239d61c154d)

**Comment by numeredev** [comment]
Das ist die logische Position vom Start des Dokuments, deswegen.

**Comment by numeredev** [comment]
You want to try with `GetColumn(GetCurrentPosition())`

**Comment by MarkRamp** [comment]
noch eine Frage, schielßen sich die Optionen STYLE_COMMENT_LINE, STYLE_COMMENT_BLOCK, STYLE_COMMENT_SECTION_LINE und STYLE_COMMENT_SECTION_BLOCK gegenseitig aus? oder kann currentPos gleichzeitig zwei oder mehrere Style Typ sein?

**Comment by numeredev** [comment]
Am besten einfach hier nachschauen: `bool NumeReEditor::isStyleType(StyleType _type, int nPos)`, aber `STYLE_COMMENT_SECTION_LINE` sollte Teil von `STYLE_COMMENT_LINE` sein (und dasselbe für `*_BLOCK`)

**Comment by MarkRamp** [comment]
sorry für die zahlreichen Fragen, aber wie sehen STYLE_COMMENT_SECTION_LINE und STYLE_COMMENT_SECTION_BLOCK aus? Ich konnte leider kein Bespiel für beiden finden.

**Comment by numeredev** [comment]
> sorry für die zahlreichen Fragen, aber wie sehen STYLE_COMMENT_SECTION_LINE und STYLE_COMMENT_SECTION_BLOCK aus? Ich konnte leider kein Beispiel für beiden finden.

`## == STYLE_COMMENT_LINE`
`#* ... *# == STYLE_COMMENT_BLOCK`
`##! == STYLE_COMMENT_SECTION_LINE` (Dokumentationskommentar)
`#*! ... *# == STYLE_COMMENT_SECTION_BLOCK` (Dokumentationskommentar)
