### ISSUE TITLE
Function to create UUIDs

### ISSUE THREAD

**Issue by numeredev** [numere-org/NumeRe#218]
### DESCRIPTION
**What does your feature request improve on? Please describe.**
It is sometimes necessary to create a UUID to uniquely identify things. A function to create such a thing, would be helpful.

**Describe the solution you'd like**
Create a function `uuid() -> STR` or similar (`getuuid()`), which returns a UUID. It might be a good idea to support not only V4 (random-based) UUIDs but also others. Then a default-valued parameter might be a good idea.

**Additional context**

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
For now, we only want to support V4 UUIDs (random based). To do so, include `https://github.com/mariusbancila/stduuid/tree/master` as an external submodule into the project. Then use the available `std::mt19937` instances to initialize the UUID generator like so:

```C++
std::mt19937& generator = getRandGenInstance();
uuids::uuid_random_generator gen{generator};

uuids::uuid const id = gen();
return uuids::to_string(id); // we do not enclose the return value in braces
```

Create a string function `strfnc_uuid()` with the signature `NOARGS` and the name `uuid()`, which will return the new ID. Get inspired by the string function `strfnc_getuilang` and search for its identifier `getuilang()` in the code (because that has to be declared a few times).

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by mstranne** [comment]
@numeredev, since we are not using C++20, std::span is not directly supported.   

> Otherwise, such as when building with C++17, std::span is not available. However, the [Microsoft Guidelines Support Library](https://github.com/Microsoft/GSL) (aka GSL) can be used for its span implementation (from which the standard version was defined). The stduuid library defaults to use this implementation if std::span is not available.

So I guess we also have to add GSL.

**Comment by numeredev** [comment]
There's a GSL variant within stduuid-Repo, Just reference that.

However, might be possible, that the newer compiler I use supports it.
