### ISSUE TITLE
[BUG] Load/Save Table with empty column 

### ISSUE THREAD

**Issue by mstranne** [numere-org/NumeRe#225]
### DESCRIPTION
**Describe the bug**
When saving a Table with an empty Column (Header and Type is specified!) and then loading, the empty Column is not loaded.

-----------------------------------------------------
### ANALYSIS
That might be related to a call to `Memory::shrink()` in `FileHeaderInfo FileAdapter::openFile(...)`, because the mentioned information is stored in file (as long as it is not related to trailing columns, because those might be ignored upon load). During writing, some error occurs, because data is written for empty columns (might be data representatons of `NAN`). The reason might be , that the end index of the `VectorIndex` inserted into `std::vector<std::complex<double>> TableColumn::getValue(...)` and similar is calculated erroneously in this case. This has to be resolved first, before the actual problem is located in the end.

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by numeredev** [comment]
There's also a problem with saving (might also be only be within the current development version)
