### ISSUE TITLE
Categorization (drop-down functionality) of table column get lost when passing / copy the table

### ISSUE THREAD

**Issue by lucasJedel** [numere-org/NumeRe#253]
In addition, possible category values that are not already occurring in the column are getting lost.

This happens when:
- `window nDialogID -set value=currentTable() -item=editTable;`
or
- `copy currentTable(_nRow, cols{}) -target=editTable();`

**(see: requirementstool-view-edit-handleEditReq.nprc)**

right now, you have to manualy GetDatatypeOfAttribute for the table, read the categories and categorize manualy:
```
copy currentTable(_nRow, cols{}) -target=editTable();
...
sAttributeName = currentTable(#, colsCatCurr{nIdx});
categories_cst{} = $inv~requirementstool~TableMetaDataHandler~GetDatatypeOfAttribute(currentTable(), sAttributeName);
editTable().categorize(nCol, categories_cst{});
```

## Analysis
The problem is located within `void CategoricalColumn::insert(const VectorIndex& idx, const TableColumn* column)`, where only the string values but not the category definitions are copied. To achieve a good behavior, one could use a deviation of `void CategoricalColumn::setCategories(const std::vector<std::string>& vCategories)`, which only appends missing categories (with a potential new ID), e.g. `void CategoricalColumn::mergeCategories(const std::vector<std::string>& vCategories)`

**Comment by numeredev** [comment]
@lucasJedel 
Passed from and to which location? Please be precise.
