### ISSUE TITLE
Automatic indentation / tab when pressing 'Enter' after a procedures, if statements, etc.

### ISSUE THREAD

**Issue by lucasJedel** [numere-org/NumeRe#257]
### DESCRIPTION
Only a small convenience feature (maybe this can already be activated somewhere?)

**Describe the solution you'd like**
Example: when pressing enter here, you get automatic indentation:
procedure $()
endprocedure

**Describe possible alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered, if any.

**Additional context**

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
(*Describe, what's the issue and which changes have to be made*)

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by numeredev** [comment]
See comment on #244
