### ISSUE TITLE
Link the stop button in the main window with the cancel button in the debugger.

### ISSUE THREAD

**Issue by raphael-sys** [numere-org/NumeRe#36]
### DESCRIPTION
**Is your change request related to a problem? Please describe.**
To me it is always a disruption when I try to stop my program and the stop button does not work because I am in a break point. 

**Describe the solution you'd like**
The functionality of the stop button in the main window and the cancel button in the debugger should be the same and be interchangeable while being in a break point or error.

**Describe possible alternatives you've considered**
It would already be an improvement to make the stop button grey while the debugger is running. Then it would at least be visible why the button is not working. The other solution would be preferred, but this one would be an improvement as well.

**Additional context**
-

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
This can be implemented by factoring out the `ID_DEBUG_CANCEL` event ID from the menu event handler, so that it can be called from the outside. Furthermore, it is necessary to provide an interface to check, whether the debugger has the control. If this is true, then the handler for the `ID_MENU_STOP_EXECUTION` event ID in the main window shall redirect the call to the debugger to cancel the calculation.

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by numeredev** [comment]
What's to be clarified here?
