### ISSUE TITLE
Run from line/cursor command

### ISSUE THREAD

**Issue by raphael-sys** [numere-org/NumeRe#38]
### DESCRIPTION
**What does your feature request improve on? Please describe.**
When debugging a certain section it would be very useful to be able to run the program from a certain starting point. Obviously this would only work for scripts and would add value to the script data type.

**Describe the solution you'd like**
Besides the `run` command I would expect to see a `run from cursor` command.
This could also be an option when right clicking in the code or a graphical option on the left side column where the line numbers are.

**Additional context**

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
This requires a set of changes:

- Providing the interface to start from a selected line in `void Script::openScript(string& _sScriptFileName)` as well as the command line interface like `start SCRIPT -set atline=LINE`
- Provide the corresponding event handler and a short cut, e.g. `SHIFT+F5`
- Ensure that the selected line is not a continued line (then search the start of the continuation)
- Ensure that the selected line is not within a control flow block (then search the start of the control flow block)
- Update the documentation wherever necessary

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by numeredev** [comment]
If it is acceptable that the state is not correct, then this is a small and easy change. However, keeping the state correct, will be difficult and -- in fact -- not change anything.

**Comment by raphael-sys** [comment]
If by state you mean runtime variables, then no, I would not expect the state to be 'saved'. On the contrary I would expect that the user changes some things and the runs from some point in the script. This is also the reason why this could only work for scripts (and yes, only if the script was run up to the relevant point beforehand).
