### ISSUE TITLE
Expression evaluation in method call

### ISSUE THREAD

**Issue by raphael-sys** [numere-org/NumeRe#40]
### DESCRIPTION
**What does your feature request improve on? Please describe.**
When calling a method it would shorten code if expressions could be evaluated inline. 
An example could be this line
`test(1,data_parsed().rows)`
where for some reason a column should be selected based on the dimension of another table.
This does currently not work and the error message is not entirely helpful.

This feature could be neglected if we want to force people to keep their code clean and split such expressions into two lines. In this case the error message could be improved to represent this intend.

**Describe the solution you'd like**
As described above the inline evaluation should work. Which commands/methods/variables should work needs to be analyzed.

**Additional context**
-

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
(*Describe, what's the issue and which changes have to be made*)

### IMPLEMENTATION
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
* Implementation: (*Describe, what you've changed*) 
* Implementation test: (*Describe the type of test, which you performed, and if it was successful*)

### DOCUMENTATION
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
* [ ] ChangesLog updated
* [ ] Code changes commented
* **Documentation articles:**
    * [ ] corresponding documentation articles updated
    * [ ] new documentation articles created
    * [ ] not needed
* **Language files:**
    * [ ] corresponding language files updated
    * [ ] not needed

### TESTS
(*Describe, which tests you performed and their outcome*)

**Comment by numeredev** [comment]
![grafik](https://user-images.githubusercontent.com/87755490/224747551-73f6fe3f-8811-4e87-aaec-1e3c77c88542.png)
Works on my machine, what's the actual problem?

**Comment by raphael-sys** [comment]
Invalid request. Feature already existed
